name: curl-unofficial # you probably want to 'snapcraft register <name>'
version: '7.58.0+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: curl - unofficial snap # 79 char long summary
description: |
        Curl - unoffical build, as a snap to enable libcurl3 to be installed on ubuntu bionic without loosing the curl command built against libcurl4
grade: stable  # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  curl:
          plugin: autotools
          source: .
          prime:
                 - -usr/include
apps:
  curl:
    command: bin/curl
    aliases: 
        - curl
    plugs:
        - network-bind
        - home
